name: checkov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
  workflow_dispatch:

jobs:

  checkov:
    runs-on: ubuntu-latest
    with:

    steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: setup terraform
       uses: hashicorp/setup-terraform@v4

     - name: terraform fmt
       run:  terraform fmt -check
       working-directory: env/dev 

     - name: terraform init
       run: terraform init -input=false
       working-directory: env/dev 

     - name: terraform validate 
       run:  terraform validate -no-color
       working-directory: env/dev

     - name: Checkov GitHub Action
       uses: bridgecrewio/checkov-action@v12
       with:
         directory: env/dev
         framework: terraform


